### ISSUE TITLE
Dfmt doesn't build with LDC

### ISSUE THREAD

**Issue by russel** [Hackerpilot/dfmt#129]
Dfmt master/HEAD compiles (mostly) fine with dmd, "make". However using LDC, "make ldc":

/home/russel/Built/lib/libphobos2-ldc-debug.a(curl-debug.o): In function `_D3std3net4curl4HTTP19_sharedStaticCtor16FZv':
/home/Checkouts/Git/Git/LDC/runtime/phobos/std/net/curl.d:2555: undefined reference to `curl_version_info'
/home/russel/Built/lib/libphobos2-ldc-debug.a(curl-debug.o): In function `_D3std3net4curl4Curl19_sharedStaticCtor18FZv':
/home/Checkouts/Git/Git/LDC/runtime/phobos/std/net/curl.d:3583: undefined reference to `curl_global_init'
/home/russel/Built/lib/libphobos2-ldc-debug.a(curl-debug.o): In function `_D3std3net4curl4Curl19_sharedStaticDtor19FZv':
/home/Checkouts/Git/Git/LDC/runtime/phobos/std/net/curl.d:3589: undefined reference to `curl_global_cleanup'

**Comment by Hackerpilot** [comment]
The reason it compiles "mostly fine" with dmd is that I haven't annotated the asm blocks with `pure`, `nothrow`, and `@nogc` so that it will keep working with LDC and dmd 2.066.1

dfmt doesn't use curl, so I'm not sure why it's even trying to link with it.

**Comment by Hackerpilot** [comment]
I just successfully built dfmt with LDC 0.15.2-beta1.

**Comment by russel** [comment]
I just updated Dfmt and get the same problem, so I think it must be an LDC issue rather than a Dfmt issue. I'll raise an issue over there in a moment or two.

Which platform are you on? Do you build LDC from source?

I am on Fedora Rawhide, building LDC from source with GCC 5.0.

**Comment by Hackerpilot** [comment]
Fedora 21, gcc 4.9.2, ldc v0.15.2-beta1 built from source.

**Comment by Hackerpilot** [comment]
I just realized that some of my recent changes don't compile with LDC, but it's not the linker error you saw.

**Comment by Hackerpilot** [comment]
After https://github.com/Hackerpilot/dfmt/commit/512cd5fb733cf46f8a6ede5b5eb22ef9ed5fc3e9 I can build with LDC again.

**Comment by russel** [comment]
I rebuilt LDC from scratch including creating a brand new build directory, and updated Dfmt to 512cd5fb733cf46f8a6ede5b5eb22ef9ed5fc3e9 and I get the same problem. I'll post an issue at LDC. If you could chip in as and when…

**Comment by qznc** [comment]
Since this is fixed (at least a workaround) in ldc, can we close this issue here? There is nothing dfmt can do.
